<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import { controlApi } from '../api'
import PageHeader from './PageHeader.vue'
import MetricCard from './MetricCard.vue'
import SectionCard from './SectionCard.vue'
import StatusBadge from './StatusBadge.vue'
import SegmentTabs from './SegmentTabs.vue'
import EmptyState from './EmptyState.vue'
import SidePanel from './SidePanel.vue'
import ConfirmDialog from './ConfirmDialog.vue'
import CandidateStageGuide from './CandidateStageGuide.vue'

const config = ref<any>(), workers = ref<any[]>([]), history = ref<any>({ versions:[] })
const catalogs = ref<any[]>([]), bindings = ref<any[]>([]), platformWorkers = ref<any[]>([])
const hostImages = ref<any[]>([]), candidates = ref<any[]>([]), archived = ref<any[]>([]), platformTypes = ref<any[]>([]), hostAgents = ref<any[]>([]), boards = ref<any[]>([])
const principal = ref<any>(), error = ref(''), loading = ref(false), syncError = ref('')
const section = ref('platforms'), showHidden = ref(false), showArchived = ref(false)
const candidateImage = ref<any>(), selectedCandidate = ref<any>(), workspaceCandidate = ref<any>(), workspace = ref<any>()
const candidateTypeChoice = ref(''), candidateCustomType = ref(''), candidateVersion = ref(''), candidateNote = ref('')
const confirmKind = ref<'release'|'force-release'|'archive'|''>()
let timer: number | undefined
const tabs = computed(() => [{id:'platforms',label:'平台概览',icon:'platform' as const},{id:'current',label:'平台配置',icon:'settings' as const},{id:'history',label:'审计记录',icon:'report' as const},{id:'workers',label:'执行资源',icon:'model' as const}])
const discovered = computed(() => hostImages.value.filter(item => item.state === 'DISCOVERED'))
const managed = computed(() => hostImages.value.filter(item => item.state === 'MANAGED'))
const activeCatalogs = computed(() => catalogs.value.filter(item => item.state === 'AVAILABLE'))
const healthyBindings = computed(() => bindings.value.filter(item => item.state === 'HEALTHY'))
function message(response:Response){ return response.status===401?'需要登录后访问管理控制台。':response.status===403?'当前账号没有此操作权限。':'请求未完成，请稍后重试。' }
async function api(path:string, options:any={}) { const response=await controlApi(path, options); return response }
function query(){ const value=new URLSearchParams(); if(showHidden.value)value.set('include_hidden','true'); if(showArchived.value)value.set('include_archived','true'); return value.size?`?${value}`:'' }
function apply(view:any){ principal.value=view.principal; hostImages.value=view.items.filter((item:any)=>item.state!=='ARCHIVED').map((item:any)=>({...item.host_image,state:item.state,catalog_id:item.catalog?.id})); candidates.value=view.items.filter((item:any)=>item.state==='INTEGRATING').map((item:any)=>item.candidate).filter(Boolean); archived.value=view.items.filter((item:any)=>item.state==='ARCHIVED').map((item:any)=>item.candidate).filter(Boolean); bindings.value=view.items.flatMap((item:any)=>item.bindings||[]); platformWorkers.value=view.items.flatMap((item:any)=>item.workers||[]) }
async function refresh(){ loading.value=true; error.value=''; try { const [current,instances,audit,view,types,catalogList,agents,boardList]=await Promise.all([api('/api/admin/analyzer-config'),api('/api/admin/worker-instances'),api('/api/admin/analyzer-config/history'),api(`/api/admin/platform-workbench${query()}`),api('/api/admin/platform-types'),api('/api/admin/platform-catalogs'),api('/api/admin/host-agents'),api('/api/admin/boards')]); config.value=current; workers.value=instances; history.value=audit; platformTypes.value=types; catalogs.value=catalogList; hostAgents.value=agents; boards.value=boardList; apply(view); syncError.value='' } catch(cause:any) { error.value=cause?.message||'请求未完成' } finally { loading.value=false } }
async function sync(){ if(section.value!=='platforms')return; try { const [view,catalogList]=await Promise.all([api(`/api/admin/platform-workbench${query()}`),api('/api/admin/platform-catalogs')]); apply(view); catalogs.value=catalogList; syncError.value='' } catch(cause:any){syncError.value=cause?.message||'同步失败'} }
function resetCandidateDraft(){ candidateTypeChoice.value='';candidateCustomType.value='';candidateVersion.value='';candidateNote.value='' }
function openCandidate(image:any){ candidateImage.value=image; resetCandidateDraft() }
async function createCandidate(){ if(!candidateImage.value||!candidateVersion.value||!candidateTypeChoice.value)return; try { await api(`/api/admin/host-images/${candidateImage.value.id}/platform-candidates`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({platform_type_id:candidateTypeChoice.value==='custom'?null:candidateTypeChoice.value,custom_platform_type:candidateTypeChoice.value==='custom'?candidateCustomType.value:null,target_version:candidateVersion.value,note:candidateNote.value})}); candidateImage.value=undefined; await refresh() } catch(cause:any){error.value=cause?.message||'创建失败'} }
async function setImageVisibility(image:any, hidden:boolean){try{await api(`/api/admin/host-images/${image.id}/visibility`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({hidden})});await sync()}catch(cause:any){error.value=cause?.message||(hidden?'隐藏失败':'取消隐藏失败')}}
async function claim(candidate:any){ try { selectedCandidate.value=await api(`/api/admin/platform-candidates/${candidate.id}/claim`,{method:'POST'}); await sync() }catch(cause:any){error.value=cause?.message||'认领失败'} }
function openWorkspace(candidate:any){ void (async()=>{ try{const data=await api(`/api/admin/platform-candidates/${candidate.id}/workspace`);workspaceCandidate.value=data.candidate;workspace.value=data.workspace}catch(cause:any){error.value=cause?.message||'读取工作区失败'} })() }
async function saveWorkspace(){ if(!workspaceCandidate.value||!workspace.value)return; try{ const updated=await api(`/api/admin/platform-candidates/${workspaceCandidate.value.id}/workspace`,{method:'PUT',headers:{'Content-Type':'application/json','If-Match':String(workspaceCandidate.value.revision)},body:JSON.stringify(workspace.value)}); workspaceCandidate.value=updated; await sync() }catch(cause:any){error.value=cause?.message||'保存失败'} }
async function integration(candidate:any){ try{await api(`/api/admin/platform-candidates/${candidate.id}/integration-runs`,{method:'POST',headers:{'If-Match':String(candidate.revision)}});await sync()}catch(cause:any){error.value=cause?.message||'检查失败'} }
async function validation(candidate:any){ try{await api(`/api/admin/platform-candidates/${candidate.id}/real-validation-runs`,{method:'POST',headers:{'If-Match':String(candidate.revision)}});await sync()}catch(cause:any){error.value=cause?.message||'验证失败'} }
async function release(){ const candidate=selectedCandidate.value; if(!candidate)return; try{ const suffix=confirmKind.value==='force-release'?'force-release':'release'; await api(`/api/admin/platform-candidates/${candidate.id}/${suffix}`,{method:'POST',headers:{'Content-Type':'application/json','If-Match':String(candidate.revision)},body:JSON.stringify({reason:confirmKind.value==='force-release'?'超级管理员受控释放':'认领人主动释放'})}); confirmKind.value=''; selectedCandidate.value=undefined; await sync() }catch(cause:any){error.value=cause?.message||'释放失败';confirmKind.value=''} }
async function archiveCandidate(){ const candidate=selectedCandidate.value; if(!candidate)return; try{await api(`/api/admin/platform-candidates/${candidate.id}/archive`,{method:'POST',headers:{'Content-Type':'application/json','If-Match':String(candidate.revision)},body:JSON.stringify({reason:'R5 浏览器验收结束，归档临时 Candidate'})});confirmKind.value='';selectedCandidate.value=undefined;await sync()}catch(cause:any){error.value=cause?.message||'归档失败';confirmKind.value=''} }
async function forceAssign(candidate:any){ const target=prompt('输入要指定的 ACTIVE 管理员标识（系统会先清理当前接入资料）'); if(!target)return; const reason=prompt('请输入指定原因（必填）'); if(!reason)return; try{await api(`/api/admin/platform-candidates/${candidate.id}/force-assign`,{method:'POST',headers:{'Content-Type':'application/json','If-Match':String(candidate.revision)},body:JSON.stringify({target_subject:target,reason})});selectedCandidate.value=undefined;await sync()}catch(cause:any){error.value=cause?.message||'指定失败'} }
function isMine(candidate:any){return candidate.claimed_by===principal.value?.subject}
function candidateTone(candidate:any){return candidate.claimed_by?'progress':'warning'}
function stateText(candidate:any){return candidate.real_validation?.status==='SUCCEEDED'?'真实验证通过':candidate.real_validation?.status==='BLOCKED'?'真实验证受阻':candidate.integration_test?.passed?'等待真实验证':'等待接入资料'}
function configured(candidate:any){return Boolean(candidate.workspace?.compile_command_template&&candidate.workspace?.board_command_template)}
watch([showHidden,showArchived],()=>void refresh()); watch(section,()=>void sync())
onMounted(()=>{void refresh();timer=window.setInterval(()=>void sync(),5000)})
onUnmounted(()=>{if(timer!==undefined)window.clearInterval(timer)})
</script>

<template>
  <section class="page governance-page">
    <div v-if="!config" class="section-card access-state"><h2>{{loading?'正在验证当前会话':error?'管理控制台暂不可用':'正在加载管理数据'}}</h2><p>管理控制台会复用当前本地会话或企业 SSO 会话。</p><button :disabled="loading" @click="refresh">重新验证当前会话</button><p v-if="error" class="error">{{error}}</p></div>
    <template v-else>
      <PageHeader title="平台管理" description="统一查看平台接入状态、已发布平台与受控执行资源。" eyebrow="平台与执行资源" />
      <p v-if="error" class="feedback error">{{error}}</p>
      <div class="governance-toolbar">
        <SegmentTabs v-model="section" :items="tabs" />
        <div class="governance-toolbar-actions">
          <StatusBadge :tone="syncError?'warning':'success'">{{syncError?'同步提醒':'同步正常'}}</StatusBadge>
          <button class="button-secondary" :disabled="loading" @click="refresh">刷新</button>
        </div>
      </div>
      <template v-if="section==='platforms'">
        <div class="metric-grid governance-metrics"><MetricCard icon="○" label="待接入镜像" :value="discovered.length" description="已发现、尚未创建候选项的镜像" /><MetricCard icon="◐" label="接入中候选项" :value="candidates.length" description="管理员人工认领和接入中的候选平台" tone="progress" /><MetricCard icon="●" label="已发布平台" :value="activeCatalogs.length" description="已审核发布的受控平台目录" tone="success" /><MetricCard icon="▦" label="健康执行绑定" :value="healthyBindings.length" description="当前 Host 可用的受控执行绑定" tone="success" /></div>
        <SectionCard title="HostAgent 与板卡" description="查看已接入 HostAgent 和可用于评估的板卡。添加板卡、运行预检，以及创建 Platform Binding 请进入专用页面。"><template #actions><RouterLink class="button-primary" to="/platform-bindings">管理 Binding 与板卡</RouterLink></template><div class="table-wrap"><table class="data-table"><thead><tr><th>HostAgent</th><th>状态</th><th>已发现镜像</th><th>Binding</th><th>就绪板卡</th><th>最近心跳</th></tr></thead><tbody><tr v-for="agent in hostAgents" :key="agent.id"><td><strong>{{agent.id}}</strong><small>{{agent.agent_version||'版本未上报'}}</small></td><td><StatusBadge :tone="agent.host_state==='ONLINE'?'success':'warning'">{{agent.host_state}}</StatusBadge></td><td>{{agent.image_count}}</td><td>{{agent.binding_count}}</td><td>{{agent.ready_board_count}}</td><td>{{agent.last_heartbeat_at||'暂无'}}</td></tr><tr v-if="!hostAgents.length"><td colspan="6">暂无已接入 HostAgent。</td></tr></tbody></table></div><div class="compact-list" v-if="boards.length"><article v-for="board in boards" :key="board.id"><div><strong>{{board.name}}</strong><small>{{board.agent_id}} · {{board.board_type}} · {{board.connection_ref}}</small></div><StatusBadge :tone="board.status==='READY'?'success':'warning'">{{board.status}}</StatusBadge></article></div></SectionCard>
        <SectionCard class="governance-workspace" title="平台接入工作区" description="候选项来自后端权威 Workbench ViewModel；从已发现镜像创建候选项、完成资料登记和验证，再提交审核发布。"><template #actions><button class="button-secondary" @click="sync">刷新状态</button></template><p v-if="syncError" class="feedback error">后台同步失败：{{syncError}}</p>
          <div class="workbench-lanes">
            <article class="workbench-lane discovered">
              <header><div><StatusBadge>可接平台候选项</StatusBadge><h3>已发现镜像</h3></div><label class="checkbox-control"><input v-model="showHidden" type="checkbox"> 显示隐藏</label></header>
              <EmptyState v-if="!discovered.length" icon="○" title="暂无可接平台候选项" description="HostAgent 下次只读上报后会自动显示在这里。" />
              <article v-for="image in discovered" :key="image.id" class="candidate-card discovered-card"><strong>{{image.image_ref}}</strong><small>{{image.agent_id}} · {{image.image_id?.slice(0,24)}}</small><div class="candidate-card-actions"><button type="button" class="candidate-link-action" @click="openCandidate(image)">创建候选项 <span>→</span></button><button type="button" class="row-secondary-action candidate-hide-action" @click="setImageVisibility(image, !image.hidden)">{{image.hidden ? '取消隐藏' : '隐藏'}}</button></div></article>
            </article>
            <article class="workbench-lane integrating">
              <header><div><StatusBadge tone="progress">接入进行中</StatusBadge><h3>候选平台</h3></div><label class="checkbox-control"><input v-model="showArchived" type="checkbox"> 显示归档</label></header>
              <EmptyState v-if="!candidates.length" icon="◐" title="暂无接入中候选平台" description="创建候选项后，将在此跟踪人工认领、资料登记与真实验证。" />
              <button v-for="candidate in candidates" :key="candidate.id" type="button" class="candidate-card" @click="selectedCandidate=candidate"><div><strong>{{candidate.package?.id||candidate.id.slice(0,18)}}</strong><StatusBadge :tone="candidateTone(candidate)">{{candidate.claimed_by?(isMine(candidate)?'我已认领':`${candidate.claimed_by_name} 已认领`):'待认领'}}</StatusBadge></div><small>{{candidate.agent_id}} · 修订 {{candidate.revision}}</small><small>{{stateText(candidate)}}</small></button>
            </article>
            <article class="workbench-lane managed"><header><div><StatusBadge tone="success">已发布</StatusBadge><h3>可用平台</h3></div></header><EmptyState v-if="!managed.length" icon="●" title="暂无已发布平台镜像" description="审核发布平台目录并建立健康执行绑定后会显示在这里。" /><article v-for="image in managed" :key="image.id" class="candidate-card managed-card"><strong>{{image.image_ref}}</strong><small>{{image.agent_id}} · Catalog {{image.catalog_id?.slice(0,18)}}</small></article></article>
          </div>
          <div class="managed-guide-row"><CandidateStageGuide stage="MANAGED" /></div>
        </SectionCard>
        <SectionCard v-if="showArchived" class="archived-candidates-section" title="已归档 Candidate" description="归档项默认不参与三态工作区。"><EmptyState v-if="!archived.length" title="暂无归档 Candidate" description="当前没有可显示的归档项。" /><div v-else class="compact-list"><article v-for="candidate in archived" :key="candidate.id"><div><strong>{{candidate.package?.id||candidate.id}}</strong><small>归档者 {{candidate.archived_by||'-'}} · {{candidate.archived_at||'-'}}</small></div></article></div></SectionCard>
        <SectionCard class="catalog-capability-section" title="已发布平台与执行能力" description="只有已发布平台目录、健康执行绑定和 READY Worker 同时满足时，平台才可供用户评估选择。"><div class="table-wrap"><table class="data-table"><thead><tr><th>平台 / 版本</th><th>固定 Runner</th><th>发布状态</th><th>执行绑定</th><th>就绪 Worker</th></tr></thead><tbody><tr v-for="catalog in catalogs" :key="catalog.id"><td><strong>{{catalog.display_name}}</strong><small>{{catalog.version}}</small></td><td>{{catalog.runner?.version||'未登记'}}</td><td><StatusBadge :tone="catalog.state==='AVAILABLE'?'success':'warning'">{{catalog.state==='AVAILABLE'?'可用':'待审核'}}</StatusBadge></td><td>{{bindings.filter(item=>item.catalog_id===catalog.id).length}}</td><td>{{platformWorkers.filter(item=>item.catalog_id===catalog.id).length}}</td></tr></tbody></table></div></SectionCard>
      </template>
      <SectionCard v-if="section==='current'" title="当前配置" description="已发布配置仅影响之后创建的任务。"><div class="metric-grid"><MetricCard icon="✓" label="活动版本" :value="`v${config.revision}`" :description="`哈希 ${config.config_hash?.slice(0,12)}`" tone="success" /><MetricCard icon="▦" label="总容量" :value="`${workers[0]?.running_containers||0} / ${config.max_concurrency}`" description="运行容器 / 配置容量" /></div></SectionCard>
      <SectionCard v-if="section==='history'" title="历史与审计" description="只展示可审计的配置变更事实。"><div class="table-wrap"><table class="data-table"><thead><tr><th>版本</th><th>哈希</th><th>创建人</th><th>说明</th></tr></thead><tbody><tr v-for="item in history.versions" :key="item.version"><td>v{{item.version}}</td><td>{{item.hash?.slice(0,12)}}</td><td>{{item.created_by}}</td><td>{{item.note}}</td></tr></tbody></table></div></SectionCard>
      <SectionCard v-if="section==='workers'" title="Worker 与租约" description="受控执行能力由平台 Binding、容量与健康状态共同决定。"><EmptyState v-if="!workers.length" title="暂无 Worker" description="HostAgent 上报后将在此显示。" /><div v-else class="table-wrap"><table class="data-table"><thead><tr><th>实例</th><th>状态</th><th>容量</th><th>队列</th><th>心跳</th></tr></thead><tbody><tr v-for="worker in workers" :key="worker.instance_id"><td>{{worker.instance_id}}</td><td><StatusBadge :tone="worker.health==='READY'?'success':worker.health==='BUSY'?'progress':'warning'">{{worker.health}}</StatusBadge></td><td>{{worker.running_containers}} / {{worker.max_concurrency}}</td><td>{{worker.queue_count}}</td><td>{{worker.last_heartbeat||'暂无运行租约'}}</td></tr></tbody></table></div></SectionCard>
      <SidePanel :open="Boolean(candidateImage)" title="创建 Candidate" @close="candidateImage=undefined"><form v-if="candidateImage" class="form-grid" @submit.prevent="createCandidate"><CandidateStageGuide stage="DISCOVERED" /><p class="panel-intro">{{candidateImage.image_ref}}</p><label>平台类型<select v-model="candidateTypeChoice" required><option disabled value="">请选择平台类型</option><option v-for="type in platformTypes" :key="type.id" :value="type.id">{{type.display_name}}</option><option value="custom">自定义平台类型</option></select></label><label v-if="candidateTypeChoice==='custom'">自定义平台类型<input v-model="candidateCustomType" required placeholder="例如 J6M"></label><label>目标版本<input v-model="candidateVersion" required placeholder="例如 1.1.0"></label><label>接入说明<input v-model="candidateNote" maxlength="500"></label><button class="button-primary">生成 Candidate</button></form></SidePanel>
      <SidePanel :open="Boolean(selectedCandidate)" :title="selectedCandidate?.package?.id||'Candidate 详情'" @close="selectedCandidate=undefined"><template v-if="selectedCandidate"><StatusBadge :tone="candidateTone(selectedCandidate)">{{selectedCandidate.claimed_by?(isMine(selectedCandidate)?'我已认领':`${selectedCandidate.claimed_by_name} 已认领`):'待认领'}}</StatusBadge><p class="panel-intro">Host：{{selectedCandidate.agent_id}} · 修订 {{selectedCandidate.revision}}</p><CandidateStageGuide stage="INTEGRATING" :claimed-by="selectedCandidate.claimed_by_name||selectedCandidate.claimed_by" :can-edit="isMine(selectedCandidate)" :validation-state="stateText(selectedCandidate)" /><dl class="detail-list"><dt>步骤 1</dt><dd>{{configured(selectedCandidate)?'平台资料已配置':'待配置'}}</dd><dt>步骤 2</dt><dd>{{selectedCandidate.integration_test?.passed?'离线契约已通过':'尚未完成'}}</dd><dt>步骤 3</dt><dd>{{stateText(selectedCandidate)}}</dd></dl><div class="panel-actions"><button v-if="selectedCandidate.actions?.includes('claim')" class="button-primary" @click="claim(selectedCandidate)">领取 Candidate</button><button v-if="selectedCandidate.actions?.includes('edit')" @click="openWorkspace(selectedCandidate)">打开接入工作区</button><button v-if="selectedCandidate.actions?.includes('test')&&!selectedCandidate.integration_test?.passed" @click="integration(selectedCandidate)">运行离线契约检查</button><button v-if="selectedCandidate.actions?.includes('test')" @click="validation(selectedCandidate)">发起真实接入验证</button><button v-if="selectedCandidate.actions?.includes('release')" class="button-danger" @click="confirmKind='release'">释放并清理资料</button><button v-if="selectedCandidate.actions?.includes('force_release')" class="button-danger" @click="confirmKind='force-release'">强制释放并清理</button><button v-if="selectedCandidate.actions?.includes('force_assign')" @click="forceAssign(selectedCandidate)">清理后指定管理员</button><button v-if="selectedCandidate.actions?.includes('archive')" class="button-secondary" @click="confirmKind='archive'">归档 Candidate</button></div><p v-if="selectedCandidate.claimed_by&&!isMine(selectedCandidate)" class="muted">当前由 {{selectedCandidate.claimed_by_name}} 人工认领，当前只读；认领人手动释放或超级管理员处理后才会变更。</p></template></SidePanel>
      <SidePanel :open="Boolean(workspaceCandidate&&workspace)" title="Candidate 接入工作区" @close="workspaceCandidate=undefined"><form v-if="workspaceCandidate&&workspace" class="form-grid" @submit.prevent="saveWorkspace"><CandidateStageGuide stage="INTEGRATING" :claimed-by="workspaceCandidate.claimed_by_name||workspaceCandidate.claimed_by" :can-edit="isMine(workspaceCandidate)" :validation-state="stateText(workspaceCandidate)" /><p class="panel-intro">登记平台资料与固定执行规则。规则是可审查的平台资料，不是用户任务命令入口。</p><label>显示名称<input v-model="workspace.display_name" maxlength="120"></label><label>接入档案说明<input v-model="workspace.archive_note" maxlength="500"></label><label>固定编译命令模板<input v-model="workspace.compile_command_template" required></label><label>固定板端验证命令模板<input v-model="workspace.board_command_template" required></label><button class="button-primary">保存步骤 1 结果</button><button type="button" @click="integration(workspaceCandidate)">步骤 2：离线契约检查</button><button type="button" :disabled="!workspaceCandidate.integration_test?.passed" @click="validation(workspaceCandidate)">步骤 3：真实接入验证</button></form></SidePanel>
      <ConfirmDialog :open="Boolean(confirmKind)" :title="confirmKind==='archive'?'归档 Candidate':confirmKind==='force-release'?'强制释放并清理':'释放并清理资料'" :description="confirmKind==='archive'?'归档后不显示在默认三态看板，历史审计与证据仍保留。':confirmKind==='force-release'?'将清理当前认领人的本次接入资料；不会将进行中的资料转交给其他管理员。':'将清理本次认领的接入资料，Candidate 回到待认领状态。'" :confirm-label="confirmKind==='archive'?'确认归档':'确认释放'" @cancel="confirmKind=''" @confirm="confirmKind==='archive'?archiveCandidate():release()" />
    </template>
  </section>
</template>
